export const data=[
  {
      id:1,
      name:"HEART",
      image:"heart.avif",
      desc:"The heart is a muscular organ in most animals. This organ pumps blood through the blood vessels...",
      img:"heart3.webp",
      detail:"heart, organ that serves as a pump to circulate the blood. It may be a straight tube, as in spiders and annelid worms,  or a somewhat more elaborate structure with one or more receiving chambers (atria) and a main pumping chamber (ventricle), as in mollusks. In fishes the heart is a folded tube, with three or four enlarged areas that correspond to the chambers in the mammalian heart. In animals with lungs—amphibians, reptiles, birds, and mammals—the heart shows various stages of evolution from a single to a double pump that circulates blood (1) to the lungs and (2) to the body as a whole.In humans and other mammals and in birds, the heart is a four-chambered double pump that is the centre of the circulatory system. In humans it is situated between the two lungs and slightly to the left of centre, behind the breastbone; it rests on the diaphragm, the muscular partition between the chest and the abdominal cavity.The heart consists of several layers of a tough muscular wall, the myocardium. A thin layer of tissue, the pericardium, covers the outside, and another layer, the endocardium, lines the inside. The heart cavity is divided down the middle into a right and a left heart, which in turn are subdivided into two chambers. The upper chamber is called an atrium (or auricle), and the lower chamber is called a ventricle. The two atria act as receiving chambers for blood entering the heart; the more muscular ventricles pump the blood out of the heart."

      
  },
  {
      id:2,
      name:"LIVER",
      image:"liver.jpg",
      desc:"The liver is a major organ only found in vertebrates which performs many essential biological functions ...",
      img:"liver2.webp",
      detail:"liver, the largest gland in the body, a spongy mass of wedge-shaped lobes that has many metabolic and secretory functions. The liver secretes bile, a digestive fluid; metabolizes proteins, carbohydrates, and fats; stores glycogen, vitamins, and other substances; synthesizes blood-clotting factors; removes wastes and toxic matter from the blood; regulates blood volume; and destroys old red blood cells.Liver tissue consists of a mass of cells tunneled through with bile ducts and blood vessels. Hepatic cells make up about 60 percent of the tissue and perform more metabolic functions than any other group of cells in the body. A second group of cells, called Kupffer cells, line the smallest channels of the liver’s vascular system and play a role in blood formation, antibody production, and ingestion of foreign particles and cellular debris.Each day the liver secretes about 800 to 1,000 ml (about 1 quart) of bile, which contains bile salts needed for the digestion of fats in the diet. Bile is also the medium for excretion of certain metabolic waste products, drugs, and toxic substances. From the liver a duct system carries bile to the common bile duct, which empties into the duodenum of the small intestine and which connects with the gallbladder, where it is concentrated and stored. The presence of fat in the duodenum stimulates the flow of bile out of the gallbladder and into the small intestine. Senescent (worn-out) red blood cells are destroyed in the liver, spleen, and bone marrow. A pigment, bilirubin, formed in the process of hemoglobin breakdown, is released into the bile, creating its characteristic greenish orange colour, and is excreted from the body through the intestine."
  },
  {
      id:3,
      name:"HANDS",
      image:"hands.jpg",
      desc:"A hand is a prehensile, multi-fingered appendage located at the end of the forearm ...",
      img:"hand2.webp",
      detail:"Each day the liver secretes about 800 to 1,000 ml (about 1 quart) of bile, which contains bile salts needed for the digestion of fats in the diet. Bile is also the medium for excretion of certain metabolic waste products, drugs, and toxic substances. From the liver a duct system carries bile to the common bile duct, which empties into the duodenum of the small intestine and which connects with the gallbladder, where it is concentrated and stored. The presence of fat in the duodenum stimulates the flow of bile out of the gallbladder and into the small intestine. Senescent (worn-out) red blood cells are destroyed in the liver, spleen, and bone marrow. A pigment, bilirubin, formed in the process of hemoglobin breakdown, is released into the bile, creating its characteristic greenish orange colour, and is excreted from the body through the intestine.The major function of the hand in all vertebrates except human beings is locomotion; bipedal locomotion in humans frees the hands for a largely manipulative function. In primates the tips of the fingers are covered by fingernails—a specialization that improves manipulation. The palms and undersides of the fingers are marked by creases and covered by ridges called palm prints and fingerprints, which function to improve tactile sensitivity and grip. The friction ridges are arranged in general patterns that are peculiar to each species but that differ in detail. No two individuals are alike, and in humans the patterns are used for identification. The thumb is usually set at an angle distinct from the other digits; in humans and the great apes it rotates at the carpometacarpal joint, and it is therefore opposable to the other fingers and may be used in combination with them to pick up small objects."
  },
  {
      id:4,
      name:"KIDNEY",
      image:"kidney.jpg",
      desc:"The kidneys are two reddish-brown bean-shaped organs found in vertebrates...",
      img:"kidney2.webp",
      detail:"kidney, in vertebrates and some invertebrates, organ that maintains water balance and expels metabolic wastes. Primitive and embryonic kidneys consist of two series of specialized tubules that empty into two collecting ducts, the Wolffian ducts (see Wolffian duct). The more advanced kidney (metanephros) of adult reptiles, birds, and mammals is a paired compact organ whose functional units, called nephrons, filter initial urine from the blood, reabsorb water and nutrients, and secrete wastes, producing the final urine, which is expelled.Reptilian and avian kidneys are made up of many tiny lobules that, in birds, are combined into three or more lobes. Collecting tubules from each lobule empty into a separate branch of the ureter. Reptiles have relatively few nephrons (from 3,000 to 30,000 in lizards), while birds have a great number (around 200,000 in a fowl, twice as many as in a mammal of comparable size).Mammalian kidneys have a somewhat granular outer section (the cortex), containing the glomeruli and convoluted tubules, and a smooth, somewhat striated inner section (the medulla), containing the loops of Henle and the collecting tubules. As the ureter enters the kidney it enlarges into a cavity, the renal pelvis; urine passes into this pelvis from the collecting tubules. Nephrons are numerous (20,000 in a mouse)."
  },
  {
      id:5,
      name:"PANCREAS",
      image:"pancrs.jpg",
      desc:"The pancreas is an organ of the digestive system and endocrine system of vertebrates. In humans..",
      img:"pancreas1.webp",
      detail:"In humans the pancreas weighs approximately 80 grams (about 3 ounces) and is shaped like a pear. It is located in the upper abdomen, with the head lying immediately adjacent to the duodenum (the upper portion of the small intestine) and the body and tail extending across the midline nearly to the spleen. In adults, most of the pancreatic tissue is devoted to exocrine function, in which digestive enzymes are secreted via the pancreatic ducts into the duodenum. The cells in the pancreas that produce digestive enzymes are called acinar cells (from Latin acinus, meaning “grape”), so named because the cells aggregate to form bundles that resemble a cluster of grapes. Located between the clusters of acinar cells are scattered patches of another type of secretory tissue, collectively known as the islets of Langerhans, named for the 19th-century German pathologist Paul Langerhans. The islets carry out the endocrine functions of the pancreas, though they account for only 1 to 2 percent of pancreatic tissue.A large main duct, the duct of Wirsung, collects pancreatic juice and empties into the duodenum. In many individuals a smaller duct (the duct of Santorini) also empties into the duodenum. Enzymes active in the digestion of carbohydrates, fat, and protein continuously flow from the pancreas through these ducts. Their flow is controlled by the vagus nerve and by the hormones secretin and cholecystokinin, which are produced in the intestinal mucosa. When food enters the duodenum, secretin and cholecystokinin are released into the bloodstream by secretory cells of the duodenum. When these hormones reach the pancreas, the pancreatic cells are stimulated to produce and release large amounts of water, bicarbonate, and digestive enzymes, which then flow into the intestine."
  },
  
{
    id:6,
    name:"EYES",
    image:"eyes.jpg",
    desc:"Eyes are organs of the visual system. They provide living organisms with vision ....",
    img:"eye1.webp",
    detail:"The eye is protected from mechanical injury by being enclosed in a socket, or orbit, which is made up of portions of several of the bones of the skull to form a four-sided pyramid, the apex of which points back into the head. Thus, the floor of the orbit is made up of parts of the maxilla, zygomatic, and palatine bones, while the roof is made up of the orbital plate of the frontal bone and, behind this, by the lesser wing of the sphenoid. The optic foramen, the opening through which the optic nerve runs back into the brain and the large ophthalmic artery enters the orbit, is at the nasal side of the apex; the superior orbital fissure is a larger hole through which pass large veins and nerves. These nerves may carry nonvisual sensory messages—e.g., pain—or they may be motor nerves controlling the muscles of the eye. There are other fissures and canals transmitting nerves and blood vessels. The eyeball and its functional muscles are surrounded by a layer of orbital fat that acts much like a cushion, permitting a smooth rotation of the eyeball about a virtually fixed point, the centre of rotation. The protrusion of the eyeballs—proptosis—in exophthalmic goitre is caused by the collection of fluid in the orbital fatty tissue.It is vitally important that the front surface of the eyeball, the cornea, remain moist. This is achieved by the eyelids, which during waking hours sweep the secretions of the lacrimal apparatus and other glands over the surface at regular intervals and which during sleep cover the eyes and prevent evaporation. The lids have the additional function of preventing injuries from foreign bodies, through the operation of the blink reflex. The lids are essentially folds of tissue covering the front of the orbit and, when the eye is open, leaving an almond-shaped aperture. The points of the almond are called canthi; that nearest the nose is the inner canthus, and the other is the outer canthus. The lid may be divided into four layers: (1) the skin, containing glands that open onto the surface of the lid margin, and the eyelashes; (2) a muscular layer containing principally the orbicularis oculi muscle, responsible for lid closure; (3) a fibrous layer that gives the lid its mechanical stability, its principal portions being the tarsal plates, which border directly upon the opening between the lids, called the palpebral aperture; and (4) the innermost layer of the lid, a portion of the conjunctiva. The conjunctiva is a mucous membrane that serves to attach the eyeball to the orbit and lids but permits a considerable degree of rotation of the eyeball in the orbit."
},

]